### 

GET http://localhost:3000/usuario

###

POST http://localhost:3000/usuario
Content-Type: application/json

{
    "name": "Pernalonga",
    "email": "P32ernalonga@gmail.com"
}

###

GET http://localhost:3000/tarefas
### 

POST http://localhost:3000/tarefas
Content-Type: application/json

{
    "id_usuario": 1,
    "setor": "setor 1",
    "data_tarefa": "10-10-2000",
    "status": "em andamento",
    "prioridade" : "alta"
}